# Generated by Django 5.1.3 on 2024-11-26 10:22

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("nickname", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "birthdate",
                    models.DateField(help_text="Įveskite gimimo datą (YYYY-MM-DD)"),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(default="LT", max_length=2),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default="profile_photos/default-user.png",
                        upload_to="profile_photos/",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("V", "Vyras"), ("M", "Moteris")], max_length=1
                    ),
                ),
                ("agrees_to_terms", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
